# Introduction To NumPy

## What is NumPy

`NumPy`, short for `Numerical Python`, is one of the most important package for numerical computing in `Python`. `Numpy` is designed for efficiency on large `array` of `data`.

- `NumPy` internally stores data in a contiguous block of `memory`, independent of other built-in Python objects. NumPy’s library of algorithms written in `C` can operate on this `memory` without any `type` checking or other overhead.


- `NumPy arrays` use less memory than built-in Python sequences.

- `NumPy` uses algorithms written in `C` that runs in nanoseconds rather than seconds.

- `NumPy` operations perform complex computations on entire `array` without the need for Python for loops.

## NumPy array vs Python List

`NumPy arrays` are faster and more compact than `Python lists`. 

`NumPy arrays` uses less memory to store `data` and supports more `data types`as compared to Python. `NumPy` provides a `dtype`parameter to define the `data type` (`int`, `float` etc).


## The `ndarray`

The most important feature of `Numpy` is the `ndarray` which stands for `multi-dimensional array` which provides vectorized arithmetic operations.

- The type of `items` in the `array` is specified by a separate `data-type object` parameter named `dtype`.

- The number of dimensions in an `array` is defined by its `shape`, which is a `tuple` of `n` non-negative integers that specify the size of each dimension.

## The Array Element Type `dtype`

The `dtype` determines how the data is interpreted as being `floating point`, `integer`, `boolean` etc.

### Creating Your First NumPy `ndarrays`

In [21]:
import numpy as np

In [33]:
np.__version__

'1.20.3'

### Range Of Values

Create an `ndarray` of one dimension with evenly spaced `values`.

In [22]:
a = np.arange(15)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
1
(15,)
int32
4


### From A List Of Values

Create a `ndarray` from a python `list`.

In [24]:
b = [i for i in range(15)]
print(b)
print(type(b))

c = np.array(b)
print(c)
print(type(c))
print(c.ndim)
print(c.shape)
print(c.dtype)
print(c.itemsize)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
<class 'list'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
1
(15,)
int32
4


### Create An Array Of Zeros

In [26]:
array_of_zeros = np.zeros(10)
print(array_of_zeros)
print(type(array_of_zeros))
print(array_of_zeros.ndim)
print(array_of_zeros.shape)
print(array_of_zeros.dtype)
print(array_of_zeros.itemsize)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
1
(10,)
float64
8


### NumPy `ndim`

`ndim`determines the dimensions of the input `ndarray`

In [4]:
a.ndim

1

### NumPy `itemsize`

determine the `size` of the array items in `byte`.

In [7]:
a.itemsize

4

### NumPy `dtype`

In [ ]:
determine the data `type` of the array items.

In [10]:
a.dtype

dtype('int32')

### NumPy `shape`

determine the `shape` of the `ndarray`. `shape` return a `tuple`.

In [20]:
shape = a.shape
print(shape)
print(type(shape))

(15,)
<class 'tuple'>


### Built-in `ndarray`  Methods

In [19]:
ndarray_methods = [method for method in dir(a) if not method.startswith("__")]
print(ndarray_methods)

['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']


### NumPy `reshape`

Create a new shape to an `ndarray` without changing its `values`.

In [15]:
a = a.reshape(3, 5)
print(a)
print(a.ndim)
print(a.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
15


### NumPy `indexing` and `slicing`

The `values` of an `array` can be accessed and assigned to the same way as other Python sequences.


In [31]:
print(a)
print(a[5])
print(a[0:2])
print(a[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
5
[0 1]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


### Data Type `dtype`

A numpy `array` may contain only a single `data-type` described by a `dtype`.

In [16]:
d = np.array(list(range(15)), dtype='int')
print(d)
print(d.dtype)

e = np.array(list(range(15)), dtype='float')
print(e)
print(e.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
int32
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
float64


## NumPy Performance

In [1]:
numpy_array = np.arange(10**6)
print(numpy_array[:10])
print(type(numpy_array))

python_list = list(range(10**6))
print(python_list[:10])
print(type(python_list))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [2]:
%time for _ in range(10): numpy_array_double = numpy_array * 2

Wall time: 40 ms


In [7]:
print(numpy_array_double[-10:])

[1999982 1999984 1999986 1999988 1999990 1999992 1999994 1999996 1999998
 2000000]


In [4]:
%time numpy_array_double = np.append(numpy_array_double, 2000000)
print(numpy_array_double[10:])

Wall time: 5 ms
[     20      22      24 ... 1999996 1999998 2000000]


In [5]:
%time for _ in range(10): python_list_double = [i * 2 for i in python_list]

Wall time: 1.62 s


In [8]:
%time python_list_double.append(2000000)
print(python_list_double[-10:])

Wall time: 0 ns
[1999984, 1999986, 1999988, 1999990, 1999992, 1999994, 1999996, 1999998, 2000000, 2000000]


## `NumPy` Concepts

### Vectorization

`Vectorization` is the process of performing the same operation in the same way for each element in an array. This removes for loops from your code but achieves the same result.

#### Example of vectorized function

In [44]:
p = np.power(a, 2)
print(p)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196]


In [45]:
m = np.multiply(a, 2)
print(m)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [46]:
s = np.sin(a)
print(s)

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736]


In [48]:
c = np.cos(a)
print(c)

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722]


### Broadcasting 

`Broadcasting` is the process of extending two arrays of different shapes and figuring out how to perform a `vectorized` calculation between them.

### Built-in NumPy Methodds

In [36]:
numpy_methods = [method for method in dir(np) if not method.startswith("_")]
print(numpy_methods)

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', 'abs', 'absolute', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc_ufunc', 'alen', 'all', 'allclose', 'alltrue', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argm

### NumPy `ufuncs`

There are currently more than `60` universal functions defined in `numpy` on one or more types, covering a wide variety of operations. 


https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

### Other Subpackages

`numpy.fft` Fast Fourier Transform

`numpy.polynomial` Efficient Polynomials

`numpy.linalg` Linear Algebra

`numpy.math` C Standard library functions

`numpy.random` Random Number Generation

### Conclusion

`NumPy` provides a wide variety of functions capable of performing operations on `arrays` of data. Its use of `vectorization` makes these functions incredibly fast, when compared to the analogous computations performed in pure Python. 