# Introduction To NumPy

## What is NumPy

`NumPy`, short for `Numerical Python`, is one of the most important package for numerical computing in `Python`. `Numpy` is designed for efficiency on large `array` of `data`.

## NumPy `ndarray` vs Python `list`

The core component in `NumPy` is the `ndarray` or `multi-dimensional array`. The `NumPy ndarray` is a high-performance multidimensional `array object` designed specifically to perform math operations, linear algebra, and probability calculations.

In `Numpy`, an `ndarray` describes a collection of elements, similar to a `list`.

`NumPy ndarray` are faster and more compact than `Python list`. 

`NumPy` operations perform complex computations on entire `ndarray` without the need for Python `for loops`.

`NumPy ndarray` uses less memory to store `data` and supports more `data types`as compared to Python.

`NumPy` uses algorithms written in `C` that perform operations in nanoseconds rather than seconds.

The `NumPy` library takes advantage of a processor feature called `Single Instruction Multiple Data` (SIMD) to process data faster.

## The `ndarray`

The fundamental object of `NumPy` is the `ndarray` which stands for `multi-dimensional array` which provides `vectorized` arithmetic operations. The word `n-dimensional` refers to the fact that `ndarrays` can have one or more dimensions. 

- The type of `values` in the `ndarray` is specified by a separate `data-type object` parameter named `dtype`.

- The number of dimensions in an `ndarray` is defined by its `shape`, which is a `tuple` of `n` non-negative integers that specify the size of each dimension.

## Import `NumPy`

In [2]:
import numpy as np

In [30]:
# Check version
np.__version__

'1.20.3'

## NumPy `ndarray` Object

To generate a new NumPy `ndarray` objects, we must call the `np.ndarray()` constructor.

### Creating a NumPy Array from a Range of Values with `np.arange`

Create an one dimension `ndarray` using `arange` function, which is similar to python's built-in `range` function.

In [4]:
# int range
a = np.arange(1, 15)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
1
(14,)
int32
4


In [5]:
# float range
a = np.arange(1.0, 15.0)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
<class 'numpy.ndarray'>
1
(14,)
float64
8


In [6]:
# step range parameter
a = np.arange(1, 15, 2)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)

[ 1  3  5  7  9 11 13]
<class 'numpy.ndarray'>
1
(7,)
int32
4


### Creating a NumPy Array from Python List with `np.array`

Create a `ndarray` from a python `list`.

In [7]:
b = [i for i in range(15)]
print(b)
print(type(b))

c = np.array(b)
print(c)
print(type(c))
print(c.ndim)
print(c.shape)
print(c.dtype)
print(c.itemsize)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
<class 'list'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
1
(15,)
int32
4


### Creating a NumPy Array of Zeros with `np.zeros`

The `np.zeros` function creates an `array` containing `n` number of `zeros`

In [8]:
# 1 Dimension np.arrays of zeros
One_dim_array_of_zeros = np.zeros(10)
print(One_dim_array_of_zeros)
print(type(One_dim_array_of_zeros))
print(One_dim_array_of_zeros.ndim)
print(One_dim_array_of_zeros.shape)
print(One_dim_array_of_zeros.dtype)
print(One_dim_array_of_zeros.itemsize)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
1
(10,)
float64
8


In [9]:
# 2 Dimensions np.arrays of zeros
Two_dim_array_of_zeros = np.zeros((3, 5))
print(Two_dim_array_of_zeros)
print(type(Two_dim_array_of_zeros))
print(Two_dim_array_of_zeros.ndim)
print(Two_dim_array_of_zeros.shape)
print(Two_dim_array_of_zeros.dtype)
print(Two_dim_array_of_zeros.itemsize)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
2
(3, 5)
float64
8


### Creating a NumPy Array of Ones with `np.ones`

In [10]:
# 1 Dimension np.arrays of ones
One_dim_array_of_ones = np.ones(10)
print(One_dim_array_of_ones)
print(type(One_dim_array_of_ones))
print(One_dim_array_of_ones.ndim)
print(One_dim_array_of_ones.shape)
print(One_dim_array_of_ones.dtype)
print(One_dim_array_of_ones.itemsize)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
1
(10,)
float64
8


In [11]:
# 2 Dimensions np.arrays of zeros
Two_dim_array_of_ones = np.ones((3, 5))
print(Two_dim_array_of_ones)
print(type(Two_dim_array_of_ones))
print(Two_dim_array_of_ones.ndim)
print(Two_dim_array_of_ones.shape)
print(Two_dim_array_of_ones.dtype)
print(Two_dim_array_of_ones.itemsize)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
2
(3, 5)
float64
8


### Creating a NumPy Array of randint values with `np.random.randint`

In [12]:
# 1 Dimension np.arrays of random int
One_dim_random_values = np.random.randint(1, 100, size=15)
print(One_dim_random_values)
print(type(One_dim_random_values))
print(One_dim_random_values.ndim)
print(One_dim_random_values.shape)
print(One_dim_random_values.dtype)
print(One_dim_random_values.itemsize)

[85 51 95 38 78 30 81 60 55 68 94 65 18 14 60]
<class 'numpy.ndarray'>
1
(15,)
int32
4


In [13]:
# 2 Dimension np.arrays of random int
two_dim_random_values = np.random.randint(1, 100, size=(3, 5))
print(two_dim_random_values)
print(two_dim_random_values)
print(type(two_dim_random_values))
print(two_dim_random_values.ndim)
print(two_dim_random_values.shape)
print(two_dim_random_values.dtype)
print(two_dim_random_values.itemsize)

[[81 95  5  6 58]
 [ 4 30 70 37 94]
 [11 10 16 93 58]]
[[81 95  5  6 58]
 [ 4 30 70 37 94]
 [11 10 16 93 58]]
<class 'numpy.ndarray'>
2
(3, 5)
int32
4


### Exploring Built-in `np.random` Methods

In [14]:
random_methods = [m for m in dir(np.random) if not m.startswith("_")]
print(random_methods)

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


### The NumPy Array Data Types `dtype`

The `dtype` determines how the `data` is interpreted as being `floating point`, `integer`, `boolean` etc.

A NumPy `array` may contain only a single `data-type`.

- `'?' Bolean`
- `'b' byte`
- `'B' unsigned byte`
- `'i' integer`
- `'u' unsigned integer`
- `'f' floating point`
- `'c' complex floating point`
- `'m' timedelta`
- `'M' datetime`
- `'U' unicode string`
- `'V' raw data`

The possible suffixes for `int`, `float` are `1`, `2`, `4`, `8`.

In [37]:
# Int 32 data type
dt_int32 = np.array(range(15), dtype='i4')
print(dt_int32)
print(dt_int32.dtype)

dt_int32 = np.array(range(15), dtype=np.int32)
print(dt_int32)
print(dt_int32.dtype)

# Int 64 data type
dt_int64 = np.array(range(15), dtype='i8')
print(dt_int64)
print(dt_int64.dtype)

# float 32 data type
dt_float32 = np.array(range(15), dtype='f4')
print(dt_float32)
print(dt_float32.dtype)

dt_float32 = np.array(range(15), dtype=np.float32)
print(dt_float32)
print(dt_float32.dtype)

# float 64 data type
dt_float64 = np.array(list(range(15)), dtype='f8')
print(dt_float64)
print(dt_float64.dtype)

dt_float64 = np.array(range(15), dtype=np.float64)
print(dt_float64)
print(dt_float64.dtype)

# boolean data type
dt_bool = np.array(range(15), dtype='?')
print(dt_bool)
print(dt_bool.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
int32
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
int32
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
int64
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
float32
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
float32
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
float64
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
float64
[False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]
bool


### Casting  an Array `dtype` with `astype`

In [ ]:
d_int = np.array(list(range(15)), dtype='i4')
print(d_int)
print(d_int.dtype)

d_float = d_int.astype('f4')
print(d_float)
print(d_float.dtype)

### NumPy `ndim`

`ndim`determines the dimensions of the input `ndarray`.

In [ ]:
One_dim_array_of_zeros.ndim

In [ ]:
Two_dim_array_of_zeros.ndim

### NumPy `itemsize`

determine the `size` of one array `item` in `byte`.

In [ ]:
One_dim_array_of_zeros.itemsize

### NumPy `dtype`

determine the data `type` of the array items.

In [ ]:
One_dim_array_of_zeros.dtype

### NumPy `shape`

determine the `shape` of the `ndarray`. `shape` return a `tuple`.

In [ ]:
shape = One_dim_array_of_zeros.shape
print(shape)
print(type(shape))

In [ ]:
shape = Two_dim_array_of_zeros.shape
print(shape)
print(type(shape))

### Exploring Built-in `ndarray`  Methods

In [ ]:
ndarray_methods = [method for method in dir(a) if not method.startswith("__")]
print(ndarray_methods)

### NumPy `reshape`

Create a new shape to an `ndarray` without changing its `values`.

In [ ]:
a = np.arange(15)
a = a.reshape(3, 5)
print(a)
print(a.ndim)
print(a.size)

### NumPy `indexing`

In a one-dimensional `array` you can access the `value` by specifying the desired `index` in square brackets, just as with Python `list`.

In [ ]:
one_dimension = np.array([1, 2, 3, 4, 5])
print(one_dimension)

print(one_dimension[2])

In a two-dimensional or multidimensional `array` you can access `values` using comma seperated tuple of indices.

In [ ]:
two_dimension = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(two_dimension)

print(two_dimension[1, 2])


### NumPy `slicing`

The `values` of an `subarrays` can be accessed using slice notation, marked by the colon `:`.

In [ ]:
v = np.arange(1, 16).reshape(3, 5)
print(v)
print("-------")
print(v[:2, :2])
print("-------")
print(v[0:, 0:1])
print("-------")
print(v[0:, 4:])

## Add new values to a NumPy `ndarray`

### Using `ndarray.append` method

The NumPy `np.append` values to the end of an `ndarray`.

In [32]:
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
np.append(e, 10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


### Using `np.insert` method

The NumPy `np.insert` values along the given axis before the given indices.

In [62]:
f = np.array(range(1, 10))
print(f)

[1 2 3 4 5 6 7 8 9]


`np.insert` return a new `ndarray`, it doesn't modify the `ndarray` passed as argument.

In [64]:
new_f = np.insert(f, 0, 0)
print(f) # unmodified ndarray after np.insert
print(new_f) # a new ndarray is assign to new_f

[0 1 2 3 4 5 6 7 8 9]


In [68]:
new_f = np.insert(new_f, 10, 10)
print(new_f)

[ 0  1  2  3  4  5  6  7  8  9 10]


## NumPy Performance

In [ ]:
numpy_array = np.arange(10**6)
print(numpy_array[:10])
print(type(numpy_array))

python_list = list(range(10**6))
print(python_list[:10])
print(type(python_list))

In [ ]:
%time for _ in range(10): numpy_array_double = numpy_array * 2

In [ ]:
print(numpy_array_double[-10:])

In [ ]:
%time numpy_array_double = np.append(numpy_array_double, 2000000)
print(numpy_array_double[10:])

In [ ]:
%time for _ in range(10): python_list_double = [i * 2 for i in python_list]

In [ ]:
%time python_list_double.append(2000000)
print(python_list_double[-10:])

## `NumPy` Concepts

### What is Vectorization?

`Vectorization` is a technique of replacing explicit `for-loops` with `array expressions`, which in this case can be computed internally with a `low-level` language.

Vectorized operations in `NumPy` use highly optimized `C` and `Fortran` functions, making for cleaner and faster Python code.

https://en.wikipedia.org/wiki/Array_programming

#### Example of vectorized function

In [ ]:
p = np.power(a, 2)
print(p)

In [ ]:
m = np.multiply(a, 2)
print(m)

In [ ]:
s = np.sin(a)
print(s)

In [ ]:
c = np.cos(a)
print(c)

### What is Broadcasting?

`Broadcasting` describes how `NumPy` operate on `arrays` with different `shapes` during arithmetic operations to perform a `vectorized` calculation between them.

`Machine learning` is one domain that can frequently take advantage of `vectorization` and `broadcasting`.

## Arithmetic with NumPy Arrays

Any arithmetic operations between equal-size arrays applies the operation element-wise:

In [ ]:
a = np.arange(1, 21).reshape((5, 4))
print(a)

In [ ]:
b = np.arange(1, 21).reshape((5, 4))
print(b)

In [ ]:
a + b

In [ ]:
a * b

In [ ]:
a / b

In [ ]:
np.random.shuffle(a)
np.random.shuffle(b)

a > b

### Exploring `NumPy` Built-in Methods

In [ ]:
numpy_methods = [method for method in dir(np) if not method.startswith("_")]
print(numpy_methods)

### NumPy `ufuncs`

There are currently more than `60` universal functions defined in `numpy` on one or more types, covering a wide variety of operations. 


https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

### Other Subpackages

`numpy.fft` Fast Fourier Transform

`numpy.polynomial` Efficient Polynomials

`numpy.linalg` Linear Algebra

`numpy.math` C Standard library functions

`numpy.random` Random Number Generation

### Conclusion

`NumPy` provides a wide variety of functions capable of performing operations on `arrays` of data. Its use of `vectorization` makes these functions incredibly fast, when compared to the analogous computations performed in pure Python. 