# Introduction To NumPy

## What is NumPy

`NumPy`, short for `Numerical Python`, is one of the most important package for numerical computing in `Python`. `Numpy` is designed for efficiency on large `array` of `data`.

- `NumPy` internally stores data in a contiguous block of `memory`, independent of other built-in Python objects. NumPy’s library of algorithms written in `C` can operate on this `memory` without any `type` checking or other overhead.


- `NumPy arrays` use less memory than built-in Python sequences.

- `NumPy` uses algorithms written in `C` that runs in nanoseconds rather than seconds.

- `NumPy` operations perform complex computations on entire `array` without the need for Python for loops.

## NumPy array vs Python List

`NumPy arrays` are faster and more compact than `Python lists`. 

`NumPy arrays` uses less memory to store `data` and supports more `data types`as compared to Python. `NumPy` provides a `dtype`parameter to define the `data type` (`int`, `float` etc).

`NumPy` uses algorithms written in `C` that perform operations in nanoseconds rather than seconds.


## The `ndarray`

The fundamental object of `NumPy` is the `ndarray` which stands for `multi-dimensional array` which provides vectorized arithmetic operations.

- The type of `items` in the `array` is specified by a separate `data-type object` parameter named `dtype`.

- The number of dimensions in an `array` is defined by its `shape`, which is a `tuple` of `n` non-negative integers that specify the size of each dimension.

## The Array Element Type `dtype`

The `dtype` determines how the `data` is interpreted as being `floating point`, `integer`, `boolean` etc.

### Creating Your First NumPy `ndarrays`

In [3]:
import numpy as np

In [4]:
np.__version__

'1.20.3'

### Range Of Values

Create an one dimension `ndarray` using `arange` function, which is similar to python's built-in `range` function.

In [32]:
# int range
a = np.arange(1, 15)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
1
(14,)
int32
4


In [34]:
# float range
a = np.arange(1.0, 15.0)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
<class 'numpy.ndarray'>
1
(14,)
float64
8


In [36]:
# step range parameter
a = np.arange(1, 15, 2)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.itemsize)

[ 1  3  5  7  9 11 13]
<class 'numpy.ndarray'>
1
(7,)
int32
4


### From A List Of Values

Create a `ndarray` from a python `list`.

In [6]:
b = [i for i in range(15)]
print(b)
print(type(b))

c = np.array(b)
print(c)
print(type(c))
print(c.ndim)
print(c.shape)
print(c.dtype)
print(c.itemsize)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
<class 'list'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
1
(15,)
int32
4


### Create An Array Of Zeros with `np.zeros`

The `np.zeros` function creates an `array` containing `n` number of `zeros`

In [15]:
# 1 Dimension np.arrays of zeros
One_dim_array_of_zeros = np.zeros(10)
print(One_dim_array_of_zeros)
print(type(One_dim_array_of_zeros))
print(One_dim_array_of_zeros.ndim)
print(One_dim_array_of_zeros.shape)
print(One_dim_array_of_zeros.dtype)
print(One_dim_array_of_zeros.itemsize)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
1
(10,)
float64
8


In [16]:
# 2 Dimensions np.arrays of zeros
Two_dim_array_of_zeros = np.zeros((3, 5))
print(Two_dim_array_of_zeros)
print(type(Two_dim_array_of_zeros))
print(Two_dim_array_of_zeros.ndim)
print(Two_dim_array_of_zeros.shape)
print(Two_dim_array_of_zeros.dtype)
print(Two_dim_array_of_zeros.itemsize)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
2
(3, 5)
float64
8


### Create An Array Of Ones with `np.ones`

In [28]:
# 1 Dimension np.arrays of ones
One_dim_array_of_ones = np.ones(10)
print(One_dim_array_of_ones)
print(type(One_dim_array_of_ones))
print(One_dim_array_of_ones.ndim)
print(One_dim_array_of_ones.shape)
print(One_dim_array_of_ones.dtype)
print(One_dim_array_of_ones.itemsize)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
1
(10,)
float64
8


In [31]:
# 2 Dimensions np.arrays of zeros
Two_dim_array_of_ones = np.ones((3, 5))
print(Two_dim_array_of_ones)
print(type(Two_dim_array_of_ones))
print(Two_dim_array_of_ones.ndim)
print(Two_dim_array_of_ones.shape)
print(Two_dim_array_of_ones.dtype)
print(Two_dim_array_of_ones.itemsize)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
2
(3, 5)
float64
8


### NumPy `ndim`

`ndim`determines the dimensions of the input `ndarray`.

In [17]:
One_dim_array_of_zeros.ndim

1

In [18]:
Two_dim_array_of_zeros.ndim

2

### NumPy `itemsize`

determine the `size` of one array `item` in `byte`.

In [24]:
One_dim_array_of_zeros.itemsize

8

### NumPy `dtype`

determine the data `type` of the array items.

In [25]:
One_dim_array_of_zeros.dtype

dtype('float64')

### NumPy `shape`

determine the `shape` of the `ndarray`. `shape` return a `tuple`.

In [26]:
shape = One_dim_array_of_zeros.shape
print(shape)
print(type(shape))

(10,)
<class 'tuple'>


In [27]:
shape = Two_dim_array_of_zeros.shape
print(shape)
print(type(shape))

(3, 5)
<class 'tuple'>


### Built-in `ndarray`  Methods

In [ ]:
ndarray_methods = [method for method in dir(a) if not method.startswith("__")]
print(ndarray_methods)

### NumPy `reshape`

Create a new shape to an `ndarray` without changing its `values`.

In [ ]:
a = a.reshape(3, 5)
print(a)
print(a.ndim)
print(a.size)

### NumPy `indexing`

In a one-dimensional `array` you can access the `value` by specifying the desired `index` in square brackets, just as with Python `list`.

In [ ]:
one_dimension = np.array([1, 2, 3, 4, 5])
print(one_dimension)

print(one_dimension[2])

In a two-dimensional or multidimensional `array` you can access `values` using comma seperated tuple of indices.

In [ ]:
two_dimension = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(two_dimension)

print(two_dimension[1, 2])


### NumPy `slicing`

The `values` of an `subarrays` can be accessed using slice notation, marked by the colon `:`.

In [ ]:
v = np.arange(1, 16).reshape(3, 5)
print(v)
print("-------")
print(v[:2, :2])
print("-------")
print(v[0:, 0:1])
print("-------")
print(v[0:, 4:])

### Data Type `dtype`

A numpy `array` may contain only a single `data-type` described by a `dtype`.

In [ ]:
d = np.array(list(range(15)), dtype='int')
print(d)
print(d.dtype)

e = np.array(list(range(15)), dtype='float')
print(e)
print(e.dtype)

## NumPy Performance

In [ ]:
numpy_array = np.arange(10**6)
print(numpy_array[:10])
print(type(numpy_array))

python_list = list(range(10**6))
print(python_list[:10])
print(type(python_list))

In [ ]:
%time for _ in range(10): numpy_array_double = numpy_array * 2

In [ ]:
print(numpy_array_double[-10:])

In [ ]:
%time numpy_array_double = np.append(numpy_array_double, 2000000)
print(numpy_array_double[10:])

In [ ]:
%time for _ in range(10): python_list_double = [i * 2 for i in python_list]

In [ ]:
%time python_list_double.append(2000000)
print(python_list_double[-10:])

## `NumPy` Concepts

### What is Vectorization?

`Vectorization` is a technique of replacing explicit `for-loops` with `array expressions`, which in this case can be computed internally with a `low-level` language.

Vectorized operations in `NumPy` use highly optimized `C` and `Fortran` functions, making for cleaner and faster Python code.

https://en.wikipedia.org/wiki/Array_programming

#### Example of vectorized function

In [ ]:
p = np.power(a, 2)
print(p)

In [ ]:
m = np.multiply(a, 2)
print(m)

In [ ]:
s = np.sin(a)
print(s)

In [ ]:
c = np.cos(a)
print(c)

### What is Broadcasting?

`Broadcasting` describes how `NumPy` operate on `arrays` with different `shapes` during arithmetic operations to perform a `vectorized` calculation between them.

`Machine learning` is one domain that can frequently take advantage of `vectorization` and `broadcasting`.

### Built-in NumPy Methodds

In [ ]:
numpy_methods = [method for method in dir(np) if not method.startswith("_")]
print(numpy_methods)

### NumPy `ufuncs`

There are currently more than `60` universal functions defined in `numpy` on one or more types, covering a wide variety of operations. 


https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

### Other Subpackages

`numpy.fft` Fast Fourier Transform

`numpy.polynomial` Efficient Polynomials

`numpy.linalg` Linear Algebra

`numpy.math` C Standard library functions

`numpy.random` Random Number Generation

### Conclusion

`NumPy` provides a wide variety of functions capable of performing operations on `arrays` of data. Its use of `vectorization` makes these functions incredibly fast, when compared to the analogous computations performed in pure Python. 